import base64
import os

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from .email_parser import strip_html

SCOPES = ["https://www.googleapis.com/auth/gmail.modify"]


class AuthError(Exception):
    pass


class GmailClient:
    def __init__(self, credentials_path: str, token_path: str):
        self._credentials_path = credentials_path
        self._token_path = token_path
        self._service = None

    def authenticate(self) -> None:
        """
        Load token.json and refresh if expired.
        Raises AuthError if the token file is missing or the refresh fails.
        The initial token must be generated by running setup_auth.py on a desktop.
        """
        if not os.path.exists(self._token_path):
            raise AuthError(
                f"token.json not found at {self._token_path}. "
                "Run setup_auth.py on your desktop to generate it, then copy it here."
            )

        creds = Credentials.from_authorized_user_file(self._token_path, SCOPES)

        if creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
                # Persist the refreshed token so we don't refresh on every run
                with open(self._token_path, "w") as f:
                    f.write(creds.to_json())
            except Exception as e:
                raise AuthError(f"Failed to refresh Gmail token: {e}")
        elif not creds.valid:
            raise AuthError(
                "Gmail token is invalid and cannot be refreshed. "
                "Re-run setup_auth.py on your desktop to generate a new token."
            )

        self._service = build("gmail", "v1", credentials=creds)

    def mark_as_read(self, message_id: str) -> None:
        """Remove the UNREAD label from a message."""
        if self._service is None:
            raise AuthError("Call authenticate() before marking emails.")
        self._service.users().messages().modify(
            userId="me",
            id=message_id,
            body={"removeLabelIds": ["UNREAD"]},
        ).execute()

    def get_unread_bill_emails(self, label_name: str) -> list[dict]:
        """
        Return all unread messages in the given Gmail label.
        Each item in the returned list is a dict with keys:
            message_id, sender, subject, body_text
        """
        if self._service is None:
            raise AuthError("Call authenticate() before fetching emails.")

        messages = self._list_all_messages(f"label:{label_name} is:unread")
        result = []
        for msg_stub in messages:
            full_msg = (
                self._service.users()
                .messages()
                .get(userId="me", id=msg_stub["id"], format="full")
                .execute()
            )
            headers = {
                h["name"].lower(): h["value"]
                for h in full_msg.get("payload", {}).get("headers", [])
            }
            body_text = self._get_message_body(full_msg.get("payload", {}))
            result.append(
                {
                    "message_id": full_msg["id"],
                    "sender": headers.get("from", ""),
                    "subject": headers.get("subject", ""),
                    "body_text": body_text,
                }
            )
        return result

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _list_all_messages(self, query: str) -> list[dict]:
        """Fetch all message stubs for a query, handling pagination."""
        messages = []
        response = (
            self._service.users()
            .messages()
            .list(userId="me", q=query, maxResults=100)
            .execute()
        )
        messages.extend(response.get("messages", []))

        while "nextPageToken" in response:
            response = (
                self._service.users()
                .messages()
                .list(
                    userId="me",
                    q=query,
                    maxResults=100,
                    pageToken=response["nextPageToken"],
                )
                .execute()
            )
            messages.extend(response.get("messages", []))

        return messages

    def _get_message_body(self, payload: dict) -> str:
        """
        Walk the Gmail API payload tree and return plain text.
        Prefers text/plain parts; falls back to text/html (stripped via BS4).
        """
        plain_parts = []
        html_parts = []
        self._collect_parts(payload, plain_parts, html_parts)

        if plain_parts:
            return "\n".join(plain_parts)
        if html_parts:
            return "\n".join(strip_html(p) for p in html_parts)
        return ""

    def _collect_parts(
        self, payload: dict, plain_parts: list, html_parts: list
    ) -> None:
        """Recursively collect text/plain and text/html body parts."""
        mime_type = payload.get("mimeType", "")

        if "parts" in payload:
            for part in payload["parts"]:
                self._collect_parts(part, plain_parts, html_parts)
        else:
            data = payload.get("body", {}).get("data", "")
            if not data:
                return
            decoded = self._decode_part(data)
            if decoded is None:
                return
            if mime_type == "text/plain":
                plain_parts.append(decoded)
            elif mime_type == "text/html":
                html_parts.append(decoded)

    def _decode_part(self, data: str) -> str | None:
        """Base64url-decode a Gmail API body part."""
        try:
            # Gmail uses URL-safe base64; pad to a multiple of 4
            padded = data + "=" * (-len(data) % 4)
            raw_bytes = base64.urlsafe_b64decode(padded)
            return raw_bytes.decode("utf-8", errors="replace")
        except Exception:
            return None
